env:
  dev
# server:
#   port: 7009
#   tomcat:
#     max-threads: 500  #tomcat工作线程数量
#     accept-count: 500 #tomcat接受排队的最大数量
#     max-connections: 200 #tomcat处理的最大连接数
#mysql日志
logging:
  level:
    com.base.micro.dao: debug
#OSS bucket
bucketName: kc-bucket   
wx:
  info:
    appId: wx2d32521842d398fd
    secret: ea73db1bb5212e98f640ca011a80ea31
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid={0}&secret={1}&code={2}&grant_type=authorization_code
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.micro.cloud.entity              # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.66:3306/kc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&multiStatementAllow=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 192.168.0.66
    port: 6379
    password: sdtg26a3
    pool:
      maxActive: 600
      maxWait: 1000
      maxIdle: 300
      minIdle: 0
    timeout: 100000  
  rabbitmq:
#    host: 47.92.135.48
#    port: 5672
#    password: '@26a3@'
#    username: systg   
     host: localhost
     port: 5672
     username: jinghao
     password: jinghao
ribbon:
  eureka:
    enabled: true  
